### ISSUE TITLE
Dockerization Hardening

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#11]

**Comment by TalonF** [comment]
P. Ranaweera, V. N. Imirth, M. Liyanage, and A. D. Jurcut, “Security as a Service Platform Leveraging Multi-Access Edge Computing Infrastructure Provisions,” researchgate.net, pp. 1–7.

Keyword – Security as a Service, Docker, Dockerization, Security, IoT
URL - https://www.researchgate.net/profile/Madhusanka_Liyanage/publication/338853880_Security_as_a_Service_Platform_Leveraging_Multi-Access_Edge_Computing_Infrastructure_Provisions/links/5e2fc88ea6fdcc309695b451/Security-as-a-Service-Platform-Leveraging-Multi-Access-Edge-Computing-Infrastructure-Provisions.pdf
