### ISSUE TITLE
CIF Literature

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#12]

**Comment by neil-unomaha** [comment]
# Potential References on CIF
**Neil Will Explore these...**

- https://www-sciencedirect-com.leo.lib.unomaha.edu/book/9780128027301/how-to-define-and-build-an-effective-cyber-threat-intelligence-capability
- https://www.paloaltonetworks.com/company/what-we-do
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/1721654.1721691
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/1086762.1086763
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/3029806.3029811
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/1457199.1457235
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/2141512.2141516
- https://dl-acm-org.leo.lib.unomaha.edu/doi/abs/10.1145/3003733.3003759

**Comment by TalonF** [comment]
J. Elmellas, “Knowledge is power: the evolution of threat intelligence,” ScienceDirect, pp. 1–5, Jul. 2016.
[1-s2.0-S1361372316300513-main.pdf](https://github.com/neil-unomaha/CIF_CYBR_8950/files/4178511/1-s2.0-S1361372316300513-main.pdf)

Keyword - CIF, Security, Threat Intelligence

**Comment by neil-unomaha** [comment]
Keywords - Cyber Threat Intelligence Capability, Super SEIM

This book services as guidance for successful development and implementation of cyber threat intelligence capability.  It derives its conclusions from the personal observations of the author.

Two critical take aways:

* It is critical that business objectives are clearly defined so that the most appropriate cyber threat intelligence capability can be built.   

* Threat Intelligence feed is different from data feed.  Often intelligence is sold when in fact it is just data.  Threat intelligence is data that has been vetted by some process or procedure and it satisfies three different requirements:
  * Relevant
  * Actionable
  * Valuable 

H. Dalziel, E. Olson, and J. Carnall, How to define and build an effective cyber threat intelligence capability. Amsterdam: Syngress, an imprint of Elsevier, 2015.

**Comment by neil-unomaha** [comment]
Keywords: Collective Intelligence, Web 2.0 Applications

1.	**Problem Statement**
There is currently no applications specifically tailored to the special education sector. An information system needs to be designed surrounding special education data—one which ingests data from a variety of different contexts and settings.  Data input must have good UX design so as to easily sift through data and to easily utilize the data to make strategic and informed decisions for the clients.  
2.	**Research Question(s)**
What is a design and implementation strategy for developing a special-purpose collective intelligence application within the domain of special education data?
3.	**Contribution:**
There is value in using the collective intelligence model in the special education sector because data is often collected in silos. A single application that ingests data from all the different sources can identify patterns and make more informed decisions on future endeavors. 
This paper identifies seven principle collective intelligence requirements:
  - Task specific representations
  - Data is the key
  - Users add value
  - Facilitate data aggregation
  - Facilitate data access
  - Facilitate access for all devices
  - The perpetual beta (continuous improvement)
4.	**Rationale**
Researchers claim that, at the time of this publication, there did not exist a tailored application to the special education sector.  
5.	**Investigative Approach:**
Developed over 18 month field trial with one student with autism.  Started with a prototype and with feedback made tweaks and increased features over time. 
6.	**Lessons Learned:**
A collective intelligence model can be applied to many different contexts—likely any context where the aggregated information from various contexts all surrounding the same issue or problem can yield revealing insights. 

D. G. Gregg, “Designing for collective intelligence,” Communications of the ACM, vol. 53, no. 4, p. 134, Jan. 2010.

**Comment by neil-unomaha** [comment]
Keywords: Threat Intelligence Sharing Platforms, Security Policies, Security
Automation, Cyber Threat Sensing and Responding, Conceptual
Integration Design




Peter Amthor, Daniel Fischer, Winfried E. Kühnhauser, and Dirk Stelzer. 2019. Automated Cyber Threat Sensing and Responding: Integrating Threat Intelligence into Security-Policy-Controlled Systems. In Proceedings of the 14th International Conference on Availability, Reliability and Security (ARES ’19). Association for Computing Machinery, New York, NY, USA, Article 86, 1–10. DOI:https://doi-org.leo.lib.unomaha.edu/10.1145/3339252.3340509
