### ISSUE TITLE
Junk Literature Review

### ISSUE THREAD

**Issue by TalonF** [neil-unomaha/CIF_CYBR_8950#14]
Please put any reviewed material in here that we do not use.

**Comment by neil-unomaha** [comment]
O'Reilly, T. What is Web 2.0: Design patterns and business models for the next generation of software. O'Reilly Media, Inc., (Sept. 30, 2005), http://www.oreillynet.com/pub/a/oreilly/tim/news/2005/09/30/what-is-web-20.html.

**Comment by neil-unomaha** [comment]
A. Weiss, “The power of collective intelligence,” netWorker, vol. 9, no. 3, pp. 16–23, Jan. 2005.

**Comment by neil-unomaha** [comment]
H. Gascon, B. Grobauer, T. Schreck, L. Rist, D. Arp, and K. Rieck, “Mining Attributed Graphs for Threat Intelligence,” Proceedings of the Seventh ACM on Conference on Data and Application Security and Privacy - CODASPY 17, 2017.

**Comment by neil-unomaha** [comment]
Kari A. Hintikka. 2008. Web 2.0 and the collective intelligence. In Proceedings of the 12th international conference on Entertainment and media in the ubiquitous era (MindTrek ’08). Association for Computing Machinery, New York, NY, USA, 163–166. DOI:https://doi-org.leo.lib.unomaha.edu/10.1145/1457199.1457235

**Comment by neil-unomaha** [comment]
Anna De Liddo, Simon Buckingham Shum, Gregorio Convertino, Ágnes Sándor, and Mark Klein. 2012. Collective intelligence as community discourse and action. In Proceedings of the ACM 2012 conference on Computer Supported Cooperative Work Companion (CSCW ’12). Association for Computing Machinery, New York, NY, USA, 5–6. DOI:https://doi-org.leo.lib.unomaha.edu/10.1145/2141512.2141516

**Comment by neil-unomaha** [comment]
Dimitrios Sisiaridis, Fabrizio Carcillo, and Olivier Markowitch. 2016. A Framework for Threat Detection in Communication Systems. In Proceedings of the 20th Pan-Hellenic Conference on Informatics (PCI ’16). Association for Computing Machinery, New York, NY, USA, Article 68, 1–6. DOI:https://doi-org.leo.lib.unomaha.edu/10.1145/3003733.3003759

**Comment by neil-unomaha** [comment]
V. Mavroeidis and S. Bromander, "Cyber Threat Intelligence Model: An Evaluation of Taxonomies, Sharing Standards, and Ontologies within Cyber Threat Intelligence," 2017 European Intelligence and Security Informatics Conference (EISIC), Athens, 2017, pp. 91-98.
doi: 10.1109/EISIC.2017.20

**Comment by neil-unomaha** [comment]
R. Trifonov, O. Nakov and V. Mladenov, "Artificial Intelligence in Cyber Threats Intelligence," 2018 International Conference on Intelligent and Innovative Computing Applications (ICONIC), Plaine Magnien, 2018, pp. 1-4.
doi: 10.1109/ICONIC.2018.8601235
keywords: {artificial intelligence;multi-agent systems;recurrent neural nets;security of data;telecommunication security;intelligent methods;cyber security;military intelligence;artificial intelligence methods;cyber attacks;cyber intelligence;cyber criminality;cyber war;operational cyber threat intelligence;Artificial intelligence;Feature extraction;Computer security;Reservoirs;Information security;Classification algorithms;Cyber Threats Intelligence;Artificial Intelligence;Behaviour Assessment;Neural Networks;Sequential Feature Selection;Remote Network Monitoring},
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=8601235&isnumber=8601084

**Comment by neil-unomaha** [comment]
S. Chandel, M. Yan, S. Chen, H. Jiang and T. Ni, "Threat Intelligence Sharing Community: A Countermeasure Against Advanced Persistent Threat," 2019 IEEE Conference on Multimedia Information Processing and Retrieval (MIPR), San Jose, CA, USA, 2019, pp. 353-359.
doi: 10.1109/MIPR.2019.00070
keywords: {business data processing;computer crime;advanced attacking skills;persistent attacking skills;cyber-attacks;analyzing malicious behavior;intelligence information;threat intelligence sharing community;low-quality shared intelligence;advanced persistent threat;APT;Conferences;Information processing;Threat Intelligence, Cyber Attack, Sharing Community, Advanced Persistent Threat, Data Sharing},
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=8695328&isnumber=8695309

**Comment by neil-unomaha** [comment]
Y. Arimatsu, Y. Ishida, K. Noda and T. Kobayashi, "Enriching API Documentation by Relevant API Methods Recommendation Based on Version History," 2018 IEEE Third International Workshop on Dynamic Software Documentation (DySDoc3), Madrid, 2018, pp. 15-16.
doi: 10.1109/DySDoc3.2018.00014
keywords: {application program interfaces;configuration management;software maintenance;system documentation;version history;application programming interfaces;API usages;code examples;standard API documentation;software change history;Documentation;History;Standards;Java;Software;Feature extraction;Computer bugs;document-generation;mining-software-version-history;software-maintenance},
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=8530115&isnumber=8530101

**Comment by neil-unomaha** [comment]
D. Spinellis, "Code Documentation," in IEEE Software, vol. 27, no. 4, pp. 18-19, July-Aug. 2010.
doi: 10.1109/MS.2010.95
keywords: {system documentation;code documentation;explanatory documentation;bespoke documentation;Documentation;Job production systems;comments;documentation;principles;tools;best practices;javadoc;POD;software engineering},
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=5484109&isnumber=5484102

**Comment by skyemakable** [comment]
A. Benharref, M. A. Serhani, S. Bouktif and J. Bentahar, "A managerial community of Web Services for management of communities of Web Services," 2010 10th Annual International Conference on New Technologies of Distributed Systems (NOTERE), Tozeur, 2010, pp. 97-104.
doi: 10.1109/NOTERE.2010.5536782
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=5536782&isnumber=5536542

**Comment by skyemakable** [comment]
S. Jonnada and J. K. Joy, "Measure your API Complexity and Reliability," 2019 IEEE 17th International Conference on Software Engineering Research, Management and Applications (SERA), Honolulu, HI, USA, 2019, pp. 104-109.
doi: 10.1109/SERA.2019.8886790
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=8886790&isnumber=8886773

**Comment by skyemakable** [comment]
V. Chang, "Design of middleware platform to enhance abilities of application systems integration," International Conference on Information Technology: Coding and Computing (ITCC'05) - Volume II, Las Vegas, NV, 2005, pp. 461-466 Vol. 2.
doi: 10.1109/ITCC.2005.123
URL: http://ieeexplore.ieee.org.leo.lib.unomaha.edu/stamp/stamp.jsp?tp=&arnumber=1425186&isnumber=30769
