### ISSUE TITLE
Palo Alto Test Environment

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#19]

**Comment by neil-unomaha** [comment]
# Palo Alto Resources

## Video Demos of Palo Alto Features
* [Next Generaetion Firewall Capabilities Demo](https://www.paloaltonetworks.com/resources/demos/ngfw-demo)
* [Panorama Demo](https://www.paloaltonetworks.com/resources/demos/panorama-demo)  
  * _(must create an account)_

## Palo Alto Trainings and Labs
* [Free Online Labs/Virtual Courses](https://www.netdevgroup.com/online/courses?vendor=Palo+Alto+Networks)
* [Online Workshop Featuring Hands on Lab](https://events.paloaltonetworks.com/#Virtual%20Test%20Drives%20in%20Americas)

I did attempt calling customer support in order to see about getting the software in order to setup a test environment.  Waiting on the phone for over 30min and left a message.  They ended up calling back when I was away from my phone. Shucks!

**Comment by skyemakable** [comment]
[Log Forwarding](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-admin/monitoring/configure-log-forwarding)
- Use external services for monitoring the firewall
- Configure firewall to forward logs
- Requires SNMP Trap server profile
- Can setup PA firewall to forward threat logs to preset syslog profile
- Threat log data would be sent in real-time


[Tips and Tricks for forwarding traffic logs to syslog server](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClRxCAK)

**Comment by TalonF** [comment]
Palo Alto will issue a 30-day trial version however it cannot be set up on a virtual machine without putting a ticket into their support team. Looking into other means.
