### ISSUE TITLE
Review Palo Alto API Documentation

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#21]

**Comment by neil-unomaha** [comment]
Brian Provided [this link to the Palo Alto API documentation](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-panorama-api.html)

**Comment by neil-unomaha** [comment]
[Amazing tutorial on using Palo Alto API](https://live.paloaltonetworks.com/t5/Blogs/Pulling-reports-using-the-XML-API/ba-p/157015)
* [This part in the video](https://www.youtube.com/watch?v=W0z8uxiI5Bg&feature=youtu.be&t=195) details the steps required to consume the Palo Alto API
  * Best practice to setup a a separate admin account SPECIFICALLY to consume the Palo Alto API
  * With that admin account: generate the associated API key

**Comment by neil-unomaha** [comment]
[Moved Comment to more appropriate issue](https://github.com/neil-unomaha/CIF_CYBR_8950/issues/22#issuecomment-588029283)

**Comment by skyemakable** [comment]
Helpful Resource Links
- [Panorama API Guide](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-panorama-api.html)
- [Tips and Tricks: Export Threat Vault using XML API](https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA10g000000ClSMCA0)
- [Different retrieve logs from a firewall using the API](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-panorama-api/pan-os-xml-api-request-types/retrieve-logs-api) 
  - Includes example
- [Query a Firewall from Panorama (API)](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-panorama-api/pan-os-xml-api-request-types/retrieve-logs-api)
- [How to Export Logs (via web interface)](https://docs.paloaltonetworks.com/pan-os/7-1/pan-os-panorama-api/pan-os-xml-api-request-types/retrieve-logs-api)

**Comment by MLHale** [comment]
This is all really helpful information. I think most of it can be incorporated into your technical plan.

**Comment by neil-unomaha** [comment]
Perhaps the solution Brian is looking for is using the publically available [Palo Alto MindMeld tool](https://www.paloaltonetworks.com/products/secure-the-network/subscriptions/minemeld).

[Info on the MindMeld tool is here](https://docs.paloaltonetworks.com/autofocus/autofocus-admin/autofocus-apps/minemeld/introduction-to-minemeld.html#id42d3be81-1e99-4c2f-8e3c-e381cff80ddf).

However, here is where the golden ticket is.  This shows [how to configure a custom miner prototype](https://live.paloaltonetworks.com/t5/MineMeld-Articles/Using-MineMeld-to-Create-a-Custom-Miner/ta-p/227694).  So for us, it would be the CIF feed, and then it is just a matter of getting the `config` section right.  More specifically:  making the regex format the returned feed into one that Palo Alto can ingest. 

- If UNO has autofocus, then mindmeld is baked in and ready to be used.  
- If UNO has not purchased the extension of autofocus, autofocus is still an open source tool created by Palo Alto. [The Mindmeld github page is here](https://github.com/PaloAltoNetworks/minemeld/wiki)

This has the potential of solving the `pull` feature from CIF to Palo Alto

[This part in this video](https://www.youtube.com/watch?v=EjI5TA1OrLk&feature=youtu.be&t=918) explains mindmeld well and makes it sound like exactly what we are looking for.

**Comment by skyemakable** [comment]
[PAN-OS REST API](https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-panorama-api/get-started-with-the-pan-os-rest-api/pan-os-rest-api.html)
- Allows you to manage firewalls and Panorama through third-party service, application, or script
- Can create, update, rename, delete objects and policies on the firewalls
- Inputs generally match that of web interface
- Can expand on this point more if deemed necessary
