### ISSUE TITLE
Visual Diagram(s) of Palo Alto - CIF relationship

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#25]

**Comment by neil-unomaha** [comment]
[This presentation I found on YouTube](https://www.youtube.com/watch?v=wrfMnGyQIU8) contains good diagrams of CIF.  Perhaps we could get in touch with this guy and request permission to use his diagrams?

**Comment by neil-unomaha** [comment]
[This presentation I found on Youtube](https://www.youtube.com/watch?v=wrfMnGyQIU8) contains good diagrams of CIF.  Perhaps we could get in touch with this guy and request permission to use his diagrams?

**Comment by neil-unomaha** [comment]
Emailed the presenter in the YouTube video above, requesting access to his diagrams/slides:

Hi John,
I am a graduate student at the University of Nebraska, and this semester I am on a group project where we are focusing on CIF. 
Upon our initial research, we came across your CIF presentation on YouTube: https://www.youtube.com/watch?v=wrfMnGyQIU8
Very nice presentation by the way!  Anyways, we really liked the diagrams you used in your presentation to describe CIF.  We wanted to see if it would be possible to use the diagrams you created in your presentation.  We would of course attribute the diagrams to you.  
This video is of course pretty old, so if you don't have the slides around anymore we can always just take some screenshots of the diagrams in the video, or attempt to replicate them ourselves.  
Thanks so much!
Sincerely,
- Neil Thorne
P.S. I wasn't sure which email to send this request to.  The slides on the youtube video has jcb@bambenekconsulting.com, but that recording is now seven years old.  Your company's website has support@bambenekconsulting.com.  I hope it was ok that I went ahead and just emailed both.

**Comment by neil-unomaha** [comment]
# Diagram in progress - To confirm with Brian
![diagram in progress](https://github.com/neil-unomaha/CIF_CYBR_8950/blob/master/Assets/Existing_Setup.png?raw=true)

**Comment by skyemakable** [comment]
Updated diagram (pending to confirm with Brian)

![image](https://user-images.githubusercontent.com/46516728/75945728-ad902d80-5e60-11ea-8fd1-db981db1027c.png)

**Comment by skyemakable** [comment]
d77a3047e9e85e5a940e1a2ce4b464572fa50bae
