### ISSUE TITLE
Process Automation Articles

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#7]

**Comment by TalonF** [comment]
J. K. Visser and H. T. Malan, “Identification of risk associated with process automation systems,” Int. J. Econ. Manag. Eng, vol. 13, no. 7, pp. 1044–1051, 2019.

Keywords - Process Automation, Risk, System Performance, Third-Party Communication, Interface Compatibility

URL - https://pdfs.semanticscholar.org/b845/bde145526fb9fff7517161337533982defc9.pdf
