### ISSUE TITLE
Systems Architecture Integration

### ISSUE THREAD

**Issue by neil-unomaha** [neil-unomaha/CIF_CYBR_8950#9]

**Comment by TalonF** [comment]
System Architecture Integration
R. T. Tiburski, L. A. Amaral, E. D. Matos, and F. Hessel, “The importance of a standard security architecture for SOA-based IoT middleware,” Institute of Electrical and Electronics Engineers, vol. 53, no. 12, pp. 20–26, Dec. 2015.
Keyword – IoT, System Architecture, Middleware, Security, Standard Architecture

URL: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7355580&isnumber=7355551
